site_name: Llama4j
site_url: https://llama4j.com
theme:
  name: material

  features:
    - navigation.footer
    - content.code.copy

  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode      

  # icon:
    # logo: fontawesome/solid/w

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.snippets:
      url_download: true      

  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true

  - admonition
  - pymdownx.details

  - toc:
      permalink: true

extra:
  social:
    - icon: simple/github
      link: https://github.com/mukel
    - icon: simple/linkedin
      link: https://linkedin.com/in/alfonso2peterssen
    - icon: simple/x
      link: https://x.com/TheMukel

copyright: Copyright &copy; 2024 Alfonso² Peterssen
